name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Surge
        run: npm install -g surge

      - name: Generate tracks.json
        run: node site/generate_tracks.js

      - name: Deploy to Surge
        run: surge ./site joecole.surge.sh --token ${{ secrets.SURGE_TOKEN }}
